version: '2'

services:
  postgres:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
  kibana:
    image: kibana:5
    ports:
      - 5601:5601
    links:
      - 'elasticsearch'
  elasticsearch:
    image: elasticsearch:5-alpine
    ports:
      - '9200:9200'
      - '9300:9300'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
